pipeline {
   environment {
     REGISTRY_ENDPOINT = "https://index.docker.io/v1/"
     IMAGE_WITH_TAG = "yellaturibabu/springboot-helm-chart"
     REGISTRY_CERTS = "registry"
   }
  agent any
  stages {
    stage('Build') {
      steps {

        echo 'Build Images''
      }
    }
    stage('Test') {
      steps {
      echo 'Build Images'
      }
    }
    stage('Image Build&Publish') {
      steps {
        echo 'Build Images'
      }
    }
   stage('deploy to dev') {
            when {
                branch 'development'
            }

            steps {
               echo 'Build Images'
            }
        }
        stage('deploy to qa') {
            when {
                branch 'master'
            }

            steps {
               echo 'Build Images'
            }
        }
     
  }
  triggers {
    pollSCM('* * * * *')
  }
}
