pipeline {
   environment {
     REGISTRY_ENDPOINT = "https://index.docker.io/v1/"
     IMAGE_WITH_TAG = "yellaturibabu/springboot-helm-chart"
     REGISTRY_CERTS = "registry"
   }
  agent any
  stages {
    stage('Build') {
      steps {

        sh 'cd demoweb; ./mvnw package'
      }
    }
    stage('Test') {
      steps {
        sh 'cd demoweb; ./mvnw test '
      }
    }
    stage('Image Build&Publish') {
      steps {
        echo 'Build Images'
        script {
          docker.withRegistry("${REGISTRY_ENDPOINT}", "${REGISTRY_CERTS}") {
            sh 'cd demoweb; docker build -t ${IMAGE_WITH_TAG} .'
            sh 'cd demoweb; docker push ${IMAGE_WITH_TAG}'
          }
        }

      }
    }
  }
  triggers {
    pollSCM('* * * * *')
  }
}
